name: Cleanup Secrets (Manual Trigger)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm history rewrite (DANGER!)'
        required: true
        default: "no"
      dry_run:
        description: 'Dry run mode (true/false): just show findings without cleanup'
        required: true
        default: "true"
      secrets_to_replace:
        description: |
          Geef 1 of meerdere échte secrets op, gescheiden met een komma.
          Voorbeeld: abc123,ghp_exampletoken456,32cb10apikey...
        required: false
      auto_push:
        description: 'Automatically push cleaned history (true/false) - DANGER!'
        required: true
        default: "false"

jobs:
  scan-and-clean:
    runs-on: ubuntu-latest
    name: Scan for secrets en eventueel herschrijf geschiedenis

    steps:
      - name: Checkout volledige repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Installeer ggshield en git-filter-repo
        run: |
          pip install --upgrade ggshield
          sudo apt-get update && sudo apt-get install -y git-filter-repo

      - name: Draai ggshield scan (verbose)
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
        run: |
          echo "🔍 Start scan met ggshield (verbose)..."
          ggshield secret scan repo . --verbose | tee scan_output.txt

      - name: Toon ggshield scan output
        run: |
          echo "📋 Bekijk de scan-output hierboven."
          echo "Zoek regels met *** of duidelijke tokens."
          echo "Voer de échte geheimen handmatig in als secrets_to_replace (gescheiden door komma's)."

      - name: Condioneel herschrijven met git-filter-repo
        if: ${{ github.event.inputs.confirm == 'yes' && github.event.inputs.dry_run != 'true' && github.event.inputs.secrets_to_replace != '' }}
        run: |
          echo "🚨 Start herschrijven van Git-geschiedenis..."

          mkdir filtered_repo && cd filtered_repo
          git clone --bare $GITHUB_WORKSPACE repo.git
          cd repo.git

          IFS=',' read -ra secrets <<< "${{ github.event.inputs.secrets_to_replace }}"
          for secret in "${secrets[@]}"; do
            trimmed=$(echo "$secret" | xargs)
            if [[ "$trimmed" == '***' || "$trimmed" == 'REDACTED' || -z "$trimmed" ]]; then
              echo "⚠️ Ongeldige of gemaskeerde waarde '$trimmed' wordt overgeslagen."
              continue
            fi
            echo "🔒 Vervang '$trimmed' met 'REDACTED'"
            git-filter-repo --force --replace-text <(echo "$trimmed==REDACTED")
          done

      - name: Complete repository replacement (if enabled)
        if: ${{ github.event.inputs.confirm == 'yes' && github.event.inputs.dry_run != 'true' && github.event.inputs.secrets_to_replace != '' && github.event.inputs.auto_push == 'true' }}
        run: |
          # Create a working directory from the cleaned bare repo
          echo "🗑️ Creating completely new repository..."
          
          # Clone the cleaned bare repo to a working directory
          git clone filtered_repo/repo.git working_repo
          cd working_repo
          
          # Configure git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Create a new orphan branch (no history)
          git checkout --orphan new-main
          git add -A
          git commit -m "Clean repository - all secrets removed from history"
          
          # Set up remote and force push this as the new main branch
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          echo "🚀 Completely replacing repository history..."
          git push origin new-main:main --force
          
          echo "✅ Repository completely replaced with clean history!"
          echo "⚠️ All collaborators need to re-clone the repository!"

      - name: Toon vervolgstappen voor gebruiker
        if: ${{ github.event.inputs.confirm == 'yes' && github.event.inputs.dry_run != 'true' && github.event.inputs.secrets_to_replace != '' && github.event.inputs.auto_push != 'true' }}
        run: |
          REPO_URL="https://github.com/${{ github.repository }}.git"
          REPO_NAME="${{ github.event.repository.name }}"
          echo ""
          echo "✅ Cleanup voltooid!"
          echo ""
          echo "📘 Volg deze stappen om te vergelijken of direct te pushen:"
          echo ""
          echo "1️⃣  Bekijk wat er veranderd is:"
          echo "    git clone filtered_repo/repo.git cleaned_repo"
          echo "    cd cleaned_repo"
          echo "    git remote add origin $REPO_URL"
          echo "    git diff origin/main..HEAD"
          echo "    git log origin/main..HEAD"
          echo ""
          echo "2️⃣  Push alle herschreven geschiedenis (⚠️ force push!):"
          echo "    cd ../repo.git"
          echo "    git push --mirror --force"
          echo ""

      - name: Geen actie uitgevoerd
        if: ${{ github.event.inputs.confirm != 'yes' || github.event.inputs.dry_run == 'true' || github.event.inputs.secrets_to_replace == '' }}
        run: |
          echo "ℹ️ Geen herschrijving uitgevoerd. Controleer of je:"
          echo "- 'confirm' op 'yes' hebt gezet"
          echo "- 'dry_run' op 'false' hebt gezet"
          echo "- minstens 1 geldige secret hebt opgegeven (gescheiden met komma's)"
          echo "- 'auto_push' op 'true' hebt gezet (optioneel voor automatisch pushen)"
