name: Cleanup Secrets (Manual Trigger)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm history rewrite (DANGER!)'
        required: true
        default: "no"
      dry_run:
        description: 'Dry run mode (true/false): just show findings without cleanup'
        required: true
        default: "true"
      secrets_to_replace:
        description: |
          Voer hier de échte secrets in (zoals je ze kent uit je eigen code),
          1 per regel. Bijvoorbeeld:
            abcdefghijklmnopqrstuvwx
            ghijklmnopqrstuvwx123456
        required: false

jobs:
  scan-and-clean:
    runs-on: ubuntu-latest
    name: Scan for secrets and eventueel herschrijf geschiedenis

    steps:
      - name: Checkout volledige repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Installeer ggshield en git-filter-repo
        run: |
          pip install --upgrade ggshield
          sudo apt-get update && sudo apt-get install -y git-filter-repo

      - name: Draai ggshield scan (verbose)
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
        run: |
          echo "🔍 Start scan met ggshield (verbose, gemaskeerd)..."
          ggshield secret scan repo . --verbose | tee scan_output.txt

      - name: Toon ggshield scan output
        run: |
          echo "📋 Bekijk de scan-output hierboven."
          echo "Zoek regels met *** en bepaal het volledige geheim in je code."
          echo "Vul die handmatig in als 'secrets_to_replace' bij het starten van deze workflow (1 per regel)."

      - name: Condioneel herschrijven met git-filter-repo
        if: ${{ github.event.inputs.confirm == 'yes' && github.event.inputs.dry_run != 'true' && github.event.inputs.secrets_to_replace != '' }}
        run: |
          echo "🚨 Start herschrijven van Git-geschiedenis..."

          mkdir filtered_repo && cd filtered_repo
          git clone --bare $GITHUB_WORKSPACE repo.git
          cd repo.git

          echo "${{ github.event.inputs.secrets_to_replace }}" | tr -d '\r' | while IFS= read -r secret; do
            if [ -n "$secret" ]; then
              echo "🔒 Vervang '$secret' met 'REDACTED'"
              git-filter-repo --force --replace-text <(echo "$secret==REDACTED")
            fi
          done

          echo "✅ Cleanup voltooid. Je kunt handmatig pushen met:"
          echo "   cd filtered_repo/repo.git && git push --mirror --force"

      - name: Geen actie uitgevoerd
        if: ${{ github.event.inputs.confirm != 'yes' || github.event.inputs.dry_run == 'true' || github.event.inputs.secrets_to_replace == '' }}
        run: |
          echo "ℹ️ Geen herschrijving uitgevoerd. Controleer of je:"
          echo "- 'confirm' op 'yes' hebt gezet"
          echo "- 'dry_run' op 'false' hebt gezet"
          echo "- minstens 1 secret hebt opgegeven in 'secrets_to_replace'"
