name: Cleanup Secrets (Manual Trigger)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm history rewrite (DANGER!)'
        required: true
        default: "no"
      dry_run:
        description: 'Dry run mode (true/false): just show findings without cleanup'
        required: true
        default: "true"

jobs:
  scan-and-clean:
    runs-on: ubuntu-latest
    name: Scan for secrets and optionally rewrite history

    steps:
      - name: Checkout full repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history required for git-filter-repo

      - name: Set up Python and git-filter-repo
        run: |
          pip install --upgrade ggshield
          sudo apt-get update && sudo apt-get install -y git-filter-repo jq

      - name: Run ggshield scan and export JSON
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
        run: |
          ggshield secret scan repo . --json > scan_output.json || true

      - name: Show findings
        run: |
          echo "🔍 Secret findings summary:"
          jq '.results[].matches[] | {match, file, line}' scan_output.json || echo "Geen secrets gevonden."

      - name: Conditionally rewrite history (only if confirm=yes and dry_run=false)
        if: ${{ github.event.inputs.confirm == 'yes' && github.event.inputs.dry_run != 'true' }}
        run: |
          if jq -e '.results[]?.matches[]?' scan_output.json > /dev/null; then
            echo "⚠️ Secrets gevonden en confirm=yes + dry_run=false → beginnen met cleanup..."
            mkdir filtered_repo && cd filtered_repo
            git clone --bare $GITHUB_WORKSPACE repo.git
            cd repo.git

            secrets=$(jq -r '.results[].matches[].match' ../../scan_output.json | sort -u)

            for secret in $secrets; do
              echo "🔒 Filtering secret: $secret"
              git-filter-repo --force --replace-text <(echo "$secret==REDACTED")
            done

            echo "✅ Cleanup voltooid. Klaar om opnieuw te pushen naar remote (handmatig)."
            echo "LET OP: je moet nu handmatig pushen: git push --force"
          else
            echo "✅ Geen secrets gevonden, geen actie nodig."
          fi
