name: Cleanup Secrets (Manual Trigger)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm history rewrite (DANGER!)'
        required: true
        default: "no"
      dry_run:
        description: 'Dry run mode (true/false): just show findings without cleanup'
        required: true
        default: "true"
      secret_to_replace:
        description: 'Voer het exacte geheim in dat je wilt overschrijven (uit je eigen code)'
        required: false

jobs:
  scan-and-clean:
    runs-on: ubuntu-latest
    name: Scan for secrets and optionally rewrite history

    steps:
      - name: Checkout volledige repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Installeer ggshield en git-filter-repo
        run: |
          pip install --upgrade ggshield
          sudo apt-get update && sudo apt-get install -y git-filter-repo

      - name: Draai ggshield scan (verbose)
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
        run: |
          echo "🔍 Voer ggshield scan uit (geen redactie)..."
          ggshield secret scan repo . --verbose | tee scan_output.txt

      - name: Toon ggshield scanresultaten
        run: |
          echo "📋 Bekijk de output hierboven. Zoek naar regels met ***."
          echo "Zoek in je eigen code naar het volledige geheim en voer dat hieronder in als 'secret_to_replace' bij het starten van deze workflow."

      - name: Herschrijf geschiedenis met git-filter-repo (alleen bij bevestiging)
        if: ${{ github.event.inputs.confirm == 'yes' && github.event.inputs.dry_run != 'true' && github.event.inputs.secret_to_replace != '' }}
        run: |
          echo "🚨 Begin herschrijven van Git-geschiedenis..."

          mkdir filtered_repo && cd filtered_repo
          git clone --bare $GITHUB_WORKSPACE repo.git
          cd repo.git

          echo "🔒 Vervang '${{ github.event.inputs.secret_to_replace }}' met 'REDACTED'"
          git-filter-repo --force --replace-text <(echo "${{ github.event.inputs.secret_to_replace }}==REDACTED")

          echo "✅ Cleanup voltooid. Je moet dit handmatig pushen met:"
          echo "   cd filtered_repo/repo.git && git push --force --mirror"

      - name: Geen actie uitgevoerd
        if: ${{ github.event.inputs.confirm != 'yes' || github.event.inputs.dry_run == 'true' || github.event.inputs.secret_to_replace == '' }}
        run: |
          echo "ℹ️ Geen herschrijving uitgevoerd. Controleer of je:"
          echo "- 'confirm' op 'yes' hebt gezet"
          echo "- 'dry_run' op 'false' hebt gezet"
          echo "- een waarde hebt ingevuld bij 'secret_to_replace'"
